### ISSUE TITLE
typescript linting error

### ISSUE THREAD

**Issue by jedwards1211** [jcoreio/toolchains#3]
```
🏠:~/gh/precise-bs (master) $ tc lint
@jcoreio/toolchain@1.0.0-beta.2
$ eslint . --ignore-pattern flow-typed/ --ext 'js,cjs,mjs,ts,tsx,cts,ctsx,mts,mtsx'

Oops! Something went wrong! :(

ESLint: 8.42.0

TypeError: Failed to load plugin '@typescript-eslint' declared in '.eslintrc.cjs » /Users/andy/gh/precise-bs/node_modules/.pnpm/@jcoreio+toolchain@1.0.0-beta.2_eslint@8.42.0/node_modules/@jcoreio/toolchain/eslint.config.cjs » /Users/andy/gh/precise-bs/node_modules/.pnpm/@jcoreio+toolchain-typescript@1.0.0-beta.2_@babel+core@7.16.0_@jcoreio+toolchain-esnext@1.0.0_qbmsjtwyrrfdpzzvvdn5sh3cke/node_modules/@jcoreio/toolchain-typescript/eslint.extends.cjs#overrides[0]': Class extends value undefined is not a constructor or null
Referenced from: /Users/andy/gh/precise-bs/node_modules/.pnpm/@jcoreio+toolchain-typescript@1.0.0-beta.2_@babel+core@7.16.0_@jcoreio+toolchain-esnext@1.0.0_qbmsjtwyrrfdpzzvvdn5sh3cke/node_modules/@jcoreio/toolchain-typescript/eslint.extends.cjs
    at Object.<anonymous> (/Users/andy/gh/precise-bs/node_modules/.pnpm/@typescript-eslint+experimental-utils@4.33.0_eslint@8.42.0_typescript@4.5.2/node_modules/@typescript-eslint/experimental-utils/dist/ts-eslint/CLIEngine.js:12:34)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/Users/andy/gh/precise-bs/node_modules/.pnpm/@typescript-eslint+experimental-utils@4.33.0_eslint@8.42.0_typescript@4.5.2/node_modules/@typescript-eslint/experimental-utils/dist/ts-eslint/index.js:14:14)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
Command failed with exit code 2: eslint . --ignore-pattern flow-typed/ --ext js,cjs,mjs,ts,tsx,cts,ctsx,mts,mtsx
```

**Comment by jedwards1211** [comment]
This should be fixed
